name: todo_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0

# Flutter packages.
flutter:
  fonts:
      - family: Raleway
        fonts:
          # - asset: lib/assets/fonts/Raleway-Regular.ttf
          - asset: lib/assets/fonts/Raleway-Bold.ttf
            # weight : 300
      - family: Rubik
        fonts:
          - asset: lib/assets/fonts/Rubik-Regular.ttf

  # Material Icons font
  uses-material-design: true

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
